### PR TITLE
!!! FEATURE: Refactor login form to Fusion

### PR DESCRIPTION
**Pull request by Sebobo**
This replace the fluid part of the frontend login with Fusion Forms and AFX.

As this is a breaking change a new major release will be necessary.

### CODE REVIEW

**Comment by Sebobo** [comment]
@mficzel I have a problem with the field names here to make it work properly.

The necessary field name in the input has to be `__authentication[Neos][Flow][Security][Authentication][Token][UsernamePassword][username]`

But it's rendered as `--flowpack_neos_frontendlogin-loginform[__authentication][Neos][Flow][Security][Authentication][Token][UsernamePassword][username]`

Can you see what I do wrong?

**Comment by Sebobo** [comment]
Maybe we should make it possible to more easily replace the css classnames.
But would be great if someone else can look at that.
Also I made it possible to translate more parts of the login as some labels were static.

**Comment by mficzel** [comment]
@Sebobo i made a pr against this branch that goes a bit further and gets rid of this plugin mess since there is absolutely no need for that https://github.com/Sebobo/Flowpack.Neos.FrontendLogin/pull/1

**Comment by mficzel** [comment]
I accidentally pushed my changes to your branch and had to force push the previous state. heere is the updated pr https://github.com/Sebobo/Flowpack.Neos.FrontendLogin/pull/2

**Comment by Sebobo** [comment]
Replaced by #26

**Pull request closed without merging**
