### PR TITLE
FEATURE: Add user management module

### PR DESCRIPTION
**Pull request by kdambekalns**
This adds a user management module to the Neos backend and allows
to delete expired users using a CLI command.

### CODE REVIEW

**Comment by kdambekalns** [comment]
This is a draft for now, as it includes the cleanup up for review as #22 - if that is merged, this one will be easier to review.

**Review by mficzel — APPROVED** [review]
I really like this and it even works on my machine. 
Also the code makes sense to me even though i did not review it in extreme detail.

**Review by markusguenther — APPROVED** [review]
Tried it after some struggle it worked fine.
Maybe rebasing would be nice because of the PSR-7 change from @kitsunet this PR is not working out of the box.

Also had a little glitch with the new react ui.
The language label was not rendered   (just in the non react part) But maybe it is an caching issue becuase the new ui uses the language data from the xliff.json.

Bildschirmfoto 2019-12-06 um 11 15 38
Bildschirmfoto 2019-12-06 um 11 15 21

**Comment by mficzel** [comment]
@markusguenther this pr is for the 3.x branch wich does not work for 5.x. I tested on 5.1 by locally merging the pr into the package master (which runs on 5.0). If merged this will probably be released as version 3.1 for Neos 4.x and as 4.1 for Neos 5.x

**Comment by markusguenther** [comment]
> @markusguenther this pr is for the 3.x branch wich does not work for 5.x. I tested on 5.1 by locally merging the pr into the package master (which runs on 5.0). If merged this will probably be released as version 3.1 for Neos 4.x and as 4.1 for Neos 5.x


Ah ok then this was my fault.
I already fixed the translation thing with the new UI. As the "old" part is using fluid renderings they don't need the content of the xliff.json.

**Pull request merged**
