### PR TITLE
New function to fetch all users with a role

### PR DESCRIPTION
**Pull request by olleharstedt**
This time with a correct pull request... ^^

### CODE REVIEW

**Comment by olleharstedt** [comment]
Just noticed I made two commits, despite using `--amend`. Fuck git.

**Comment by bwaidelich** [comment]
@olleharstedt Thanks for this new Pull Request!
There are some minor issues with the new finder method, but more importantly:
The `UserRepository` is not meant to be used directly. Instead the `FrontendUserService` should be the central authority to interact with user entities.
I see your use case and I can try to extend _this_ package by something like `FrontendUserService::getUsersByRole()` but actually this is just a very basic example that is not meant to be used as is. The reason is that the _User_ model is part of _your_ domain and you most probably need some custom properties anyways  (or maybe in your case the User:Account relation is not N:N but 1:1).
Having said that I think the `UserService` of Neos should be extended in order to make it easier to use it with other providers/users.

**Comment by olleharstedt** [comment]
> The UserRepository is not meant to be used directly. Instead the FrontendUserService should be the central authority to interact with user entities.

Why? Isn't that just an abstraction layer extra?

OK, so no more pull-requests? I'll just continue on my own fork instead.

**Comment by bwaidelich** [comment]
It's meant to be the common API
Sure, Pull Requests are great. But don't forget that this is just a simple package for the purpose of demonstrating the FE Login.. After the discussion on Slack I think we could even reduce the functionality of this, only providing the login/logout form plugins and move the user related stuff to a new Flowpack package as common ground to start from.  Until then it's probably best if you add features you need to your fork.
Thanks again

**Pull request closed without merging**
